config/routes.rb
Rails.application.routes.draw do

  resources :movies, only: :show
  resources :people, only: :show

  match "search", to: "search#index", via: :get

  # You can have the root of your site routed with "root"
  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

#  before_filter :set_config
#
#  def set_config
#   @configuration = Tmdb::Configuration.new
#  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @now_playing = Tmdb::Movie.popular
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    @movie = Tmdb::Movie.detail(params[:id])
    @images = Tmdb::Movie.images(params[:id])
    @cast = Tmdb::Movie.casts(params[:id])
    @trailers = Tmdb::Movie.trailers(params[:id])
    @similar_movies = Tmdb::Movie.similar_movies(params[:id])
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
  @osoba = Tmdb::Person.detail(params[:id])
  @zdj = Tmdb::Person.images(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @movies = Tmdb::Movie.find(params[:query])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  TmdbConfiguration = Tmdb::Configuration.new

  # <%= image_tag("#{@configuration.base_url}w154#{image['file_path']}") if image['file_path'] %>
  # <%= image_tag("#{@configuration.base_url}w92#{movie['poster_path']}") if movie['poster_path'] %>
  def movie_poster(path)
    if path
      image_tag("#{TmdbConfiguration.base_url}w154#{path}")
    else
      ""
    end
  end

  # <%= image_tag("#{@configuration.base_url}w300#{cast['profile_path']}") if cast['profile_path'] %>
  def cast_poster(path)
    if path
      image_tag("#{TmdbConfiguration.base_url}w300#{path}")
    else
      ""
    end
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/index.html.erb
<h1>Search for a movie</h1>

<%= form_tag("/search", method: :get) do  %>
   <%= text_field_tag :query, nil %>
   <%= button_tag(type="submit" )  %>
<% end %>

<h1>Popularne filmy</h1>

<% @now_playing.first(10).each do |movie| %>
  <% if movie %>
     <%= link_to movie_path(movie['id']) do %>
       <%= movie_poster movie['poster_path'] %>
     <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMovies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/show.html.erb
<h3>Poster</h3>

<%= movie_poster @movie.poster_path %>

<h3>Facts</h3>
<% if @movie.budget>=2 %>
<p>Budget:  $<%= number_with_delimiter(@movie.budget, :delimiter => ',') %>
<% end %>
<% if @movie.revenue>=2 %>
<p>Revenue: $<%= number_with_delimiter(@movie.revenue, :delimiter => ',') %>
<% end %>
<p>Status: <%= @movie.status %>
<p>Runtime: <%= @movie.runtime %>
<p>Release Date: <%= @movie.release_date.to_date.strftime("%d/%m/%Y") if @movie.release_date %>

<h2>Trailers</h2>
<% @trailers['youtube'].each do |trailer| %>
  <p><%= link_to "#{trailer['name']} - #{trailer['size']}", "http://www.youtube.com/watch?v=#{trailer['source']}" %>
<% end %>

<h2><%= @movie.title %></h2>
<div id="star" data-score="<%= @movie.vote_average %>"></div>
<p><%= @movie.vote_average %> from <%= @movie.vote_count %> voters.

<h3>Overview</h3>
<p><%= @movie.overview %>

<h3>Tagline</h3>
<p><%= @movie.tagline %>

<h3>Images</h3>
<p><%= cast_poster @images %>

<h3>Genres</h3>
<p><% @movie.genres.each do |genre| %>
  <%= genre['name'] %>
<% end %>

<h3>Casts</h3>
<table>
  <% @cast.first(5).each do |cast| %>
  <tr>
    <td>
      <%= cast_poster cast['profile_path'] %>
      <% unless cast['profile_path'] %>
        <img src="http://placehold.it/154x154">
      <% end %>
    </td>
    <td>
      <%= link_to cast['name'], person_path(cast['id']) %> as <%= cast['character'] %>
    </td>
  </tr>
  <% end %>
</table>

<% if @similar_movies %>
  <h3>Similar Movies</h3>

   <% @similar_movies.first(8).each do |movie| %>
     <% if movie %>
        <%= link_to movie_path(movie['id']) do %>
          <%= movie_poster movie['poster_path'] %>
        <% end %>
     <% end %>
   <% end %>
<% end %>

app/views/people/show.html.erb
<h1>Dane osoby <%= @osoba.name  %></h1>
<%= movie_poster @osoba.profile_path  %>
<h2>Miejsce urodzenia:</h2>
<%= @osoba.place_of_birth  %>
<h2>Data urodzin</h2>
<%= @osoba.birthday  %>
<% if @osoba.deathday.length>=2 %>
<h2>Data śmierci</h2>
<%= @osoba.deathday %>
<% end %>
<% if @osoba.homepage.length>=2 %>
<h2>Strona internetowa:</h2> 
<%= link_to @osoba.homepage, @osoba.homepage %>
<% end %>


 

app/views/search/index.html.erb
<h1>Wyniki Wyszukiwania</h1>
<table>
  <% @movies.each do |movie| %>
  <tr>
    <td>
      <%= link_to movie_path(movie.id) do %>
        <%= movie_poster movie.poster_path %>
      <% end %>
    </td>
    <td>
      <%= link_to movie.title, movie_path(movie.id) %> <br>
      Directors: <% Tmdb::Movie.crew(movie.id).each do |crew| %> <% if crew['department'] == 'Directing' %> <%= link_to crew['name'], person_path(crew['id']) %> <% end %><% end %><br>
      Starring: <% Tmdb::Movie.casts(movie.id).first(3).each do |cast| %> <%= link_to cast['name'], person_path(cast['id']) %> | <% end %><br>
    </td>
  </tr>
  <% end %>
</table>